default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta_testflight do
    increment_build_number(xcodeproj: "Steam.xcodeproj")
    build_app(
      workspace: "Steam.xcworkspace",
      scheme: "Steam",
      export_xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new beta build to Diawi"
  lane :beta_diawi do
    increment_build_number(xcodeproj: "Steam.xcodeproj")
    build_app(
      workspace: "Steam.xcworkspace",
      scheme: "Steam",
      export_xcargs: "-allowProvisioningUpdates",
      export_method: "ad-hoc"
    )
    diawi(
      token: "pqSeqknd0bFGv0tUoeFFUgvopVvpX7R1rAuHV8AqxM"
    )
  end

end
